Improvements
gillstrom/deku-cookies pull request #2
Opened 2017-08-09 07:39 UTC by gillstrom

* Minor tweaks
* Allow changing name of cookie
* Add attribute to set a secure cookie

2017-08-09 15:14 UTC, kevva commented
Might as well do the following too:

* Use tabs in `package.json`
* Add `.npmrc` with `package-lock=false` and add `yarn.lock` to `.gitignore`
* Remove `"esnext": true` from `package.json` (`true` by default)

2017-08-09 15:14 UTC, kevva requested changes

2017-08-09 15:14 UTC, kevva commented on readme.md
> +Type: `boolean`
Default: `false`?

2017-08-10 06:16 UTC, gillstrom commented on readme.md
> +Type: `boolean`
Fixed

2017-08-10 06:16 UTC, gillstrom commented
Fixed the meta tweaks.

2017-08-10 06:28 UTC, kevva approved these changes

2017-08-10 06:28 UTC, kevva commented
LGTM 👍

2017-08-10 06:33 UTC, merged